#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H



#ifdef __cplusplus
extern "C" {
#endif

/* Values copied from the working-tree baseline. Do not retune in this refactor. */
#define LIMIT_GPIO_STATIC_TEST 0U
#define LIMIT_GPIO_POLL_PERIOD_MS 10U
#define SERIAL_TEST_FRAME_SIZE 14U
#define SERIAL_PROTOCOL_STAGE1_TEST 1U
#define SERIAL_MOTION_MIN_SPEED_HZ 1000U
#define SERIAL_MOTION_MAX_SPEED_HZ 10000U
#define SERIAL_MOTION_MAX_DISTANCE_STEPS 12000U
#define SERIAL_MOTION_MAX_TIME_SECONDS 5U
#define SERIAL_MOTION_TIMER_HZ 1000000U
/* Verification value only; tune after X-axis acceleration testing. */
#define SERIAL_MOTION_ACCELERATION_STEPS_S2 10000U
#define SERIAL_MOTION_DECELERATION_STEPS_S2 10000U
#define SERIAL_MOTION_PROFILE_ACCEL 1U
#define SERIAL_MOTION_PROFILE_CRUISE 2U
#define SERIAL_MOTION_PROFILE_DECEL 3U
#define SERIAL_MOTION_ERROR_NONE 0U
#define SERIAL_MOTION_ERROR_FRAME 1U
#define SERIAL_MOTION_ERROR_AXIS 2U
#define SERIAL_MOTION_ERROR_DIRECTION 3U
#define SERIAL_MOTION_ERROR_SPEED 4U
#define SERIAL_MOTION_ERROR_DISTANCE 5U
#define SERIAL_MOTION_ERROR_TIME 6U
#define SERIAL_MOTION_ERROR_BUSY 7U
#define SERIAL_MOTION_ERROR_TMC 8U
#define SERIAL_MOTION_ERROR_TIMER 9U
#define SERIAL_MOTION_ERROR_NOT_ACTIVE 10U
#define SERIAL_MOTION_ERROR_LIMIT 11U
#define SERIAL_AUX_ERROR_NONE 0U
#define SERIAL_AUX_ERROR_FRAME 1U
#define SERIAL_AUX_ERROR_ACTION 2U
#define SERIAL_AUX_ERROR_DATA 3U
#define SERIAL_MOTION_STATE_IDLE 0U
#define SERIAL_MOTION_STATE_PENDING 1U
#define SERIAL_MOTION_STATE_ACTIVE 2U
#define SERIAL_MOTION_STATE_DONE 3U
#define SERIAL_MOTION_STATE_ERROR 4U
#define SERIAL_MOTION_STATE_STOPPED 5U
#define SERIAL_MOTION_STATE_LIMIT_STOPPED 6U
#define SERIAL_MOTION_VALIDATION_COMMAND_ENABLED 1U
#define X_LIMIT_ACTIVE_MASK 0x0007U
#define X_MOTION_TEST_DURATION_MS 1200U
#define X_MOTION_TEST_DISABLE_DELAY_MS 6000U
#define X_MOTION_IHOLD 0U
#define X_MOTION_IRUN 3U

#define SERIAL_TX_TIMEOUT_MS 100U
#define SERIAL_BUILD_MARKER 0x20260826U
#define SERIAL_MOTION_GSTAT_CLEAR_DELAY_MS 100U
#define SERIAL_MOTION_ENABLE_DELAY_MS 200U
#define SERIAL_MOTION_DIRECTION_DELAY_MS 1U
#define X_SELF_TEST_SPI_DELAY_MS 100U
#define X_SELF_TEST_CLEAR_DELAY_MS 100U
#define X_SELF_TEST_ENABLE_DELAY_MS 200U
#define X_SELF_TEST_STEP_DELAY_MS 1U
#define X_SELF_TEST_STEP_GAP_MS 49U
#define X_SELF_TEST_STEP_COUNT 16U
#define X_SELF_TEST_REVERSE_DELTA 0x03F0U
#define X_MOTION_TOFF 3U
#define SERIAL_REQUEST_HEAD 0x55U
#define SERIAL_REQUEST_TAIL 0xAAU
#define SERIAL_RESPONSE_HEAD 0xAAU
#define SERIAL_RESPONSE_TAIL 0x55U
#define SERIAL_COMMAND_TEST 0x01U
#define SERIAL_COMMAND_MOTION 0x02U
#define SERIAL_COMMAND_RELAY 0x03U
#define SERIAL_COMMAND_BRAKE 0x04U
#define SERIAL_COMMAND_LIGHT 0x05U
#define SERIAL_SUBCOMMAND_DEFAULT 0x00U
#define SERIAL_SUBCOMMAND_STOP 0x02U
#define SERIAL_SUBCOMMAND_STATUS 0x03U
#define SERIAL_SUBCOMMAND_CONTINUOUS 0xF0U
#define SERIAL_MOTION_AXIS_X 0x01U
#define SERIAL_MOTION_DIRECTION_MAX 0x01U
#define SERIAL_STATUS_ACCEPTED 0x00U
#define SERIAL_STATUS_DONE 0x01U
#define SERIAL_STATUS_STOPPED 0x02U
#define SERIAL_STATUS_ERROR 0xFFU
#define SERIAL_AUX_ACTION_ON 0x01U
#define SERIAL_AUX_ACTION_OFF 0x02U
#define SERIAL_DATA_ZERO 0x00U
#define SERIAL_DATA_SIZE 8U
#define SERIAL_DATA_FIRST 4U
#define SERIAL_DATA_SECOND 5U
#define SERIAL_TAIL_FIRST 12U

/* Fixed byte positions; keep the original integer literal types. */
#define SERIAL_FRAME_HEAD0_INDEX 0
#define SERIAL_FRAME_HEAD1_INDEX 1
#define SERIAL_FRAME_COMMAND_INDEX 2
#define SERIAL_FRAME_SUBCOMMAND_INDEX 3
#define SERIAL_FRAME_DATA0_INDEX 4
#define SERIAL_FRAME_DATA1_INDEX 5
#define SERIAL_FRAME_DATA2_INDEX 6
#define SERIAL_FRAME_DATA3_INDEX 7
#define SERIAL_FRAME_DATA4_INDEX 8
#define SERIAL_FRAME_DATA5_INDEX 9
#define SERIAL_FRAME_DATA6_INDEX 10
#define SERIAL_FRAME_DATA7_INDEX 11
#define SERIAL_FRAME_TAIL0_INDEX 12
#define SERIAL_FRAME_TAIL1_INDEX 13
#define SERIAL_BYTE1_SHIFT 8
#define SERIAL_BYTE2_SHIFT 16
#define SERIAL_BYTE3_SHIFT 24
#define X_SELF_TEST_PHASE_IDLE 0U
#define X_SELF_TEST_PHASE_WAIT_RISE 1U
#define X_SELF_TEST_PHASE_HIGH 2U
#define X_SELF_TEST_PHASE_LOW 3U
#define X_SELF_TEST_MOTION_IDLE 0U
#define X_SELF_TEST_MOTION_RUNNING 1U

#ifdef __cplusplus
}
#endif

#endif /* MOTOR_CONFIG_H */
