#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

/* Values copied from the working-tree baseline. Do not retune in this refactor. */
/* EE-SX951P-R OUT1 is selected: MCU high means limit/fault active. */
#define LIMIT_GPIO_ACTIVE_LEVEL 1U
#define LIMIT_GPIO_EXTI_PRIORITY 1U
#define LIMIT_GPIO_EXTI_SUBPRIORITY 0U
#define SERIAL_TEST_FRAME_SIZE 14U
#define SERIAL_MOTION_MIN_SPEED_HZ 1000U
#define SERIAL_MOTION_MAX_SPEED_HZ 10000U
#define SERIAL_MOTION_MAX_DISTANCE_STEPS 12000U
#define SERIAL_MOTION_MAX_TIME_SECONDS 5U
#define SERIAL_MOTION_TIMER_HZ 1000000U
/* Verification value only; tune after axis-specific acceleration testing. */
#define SERIAL_MOTION_ACCELERATION_STEPS_S2 10000U
#define SERIAL_MOTION_DECELERATION_STEPS_S2 10000U
#define SERIAL_MOTION_PROFILE_ACCEL 1U
#define SERIAL_MOTION_PROFILE_CRUISE 2U
#define SERIAL_MOTION_PROFILE_DECEL 3U
#define SERIAL_MOTION_ERROR_NONE 0U
#define SERIAL_MOTION_ERROR_FRAME 1U
#define SERIAL_MOTION_ERROR_AXIS 2U
#define SERIAL_MOTION_ERROR_DIRECTION 3U
#define SERIAL_MOTION_ERROR_SPEED 4U
#define SERIAL_MOTION_ERROR_DISTANCE 5U
#define SERIAL_MOTION_ERROR_TIME 6U
#define SERIAL_MOTION_ERROR_BUSY 7U
#define SERIAL_MOTION_ERROR_TMC 8U
#define SERIAL_MOTION_ERROR_TIMER 9U
#define SERIAL_MOTION_ERROR_NOT_ACTIVE 10U
#define SERIAL_MOTION_ERROR_LIMIT 11U
#define SERIAL_AUX_ERROR_NONE 0U
#define SERIAL_AUX_ERROR_FRAME 1U
#define SERIAL_AUX_ERROR_ACTION 2U
#define SERIAL_AUX_ERROR_DATA 3U
#define SERIAL_MOTION_STATE_IDLE 0U
#define SERIAL_MOTION_STATE_PENDING 1U
#define SERIAL_MOTION_STATE_ACTIVE 2U
#define SERIAL_MOTION_STATE_DONE 3U
#define SERIAL_MOTION_STATE_ERROR 4U
#define SERIAL_MOTION_STATE_STOPPED 5U
#define SERIAL_MOTION_STATE_LIMIT_STOPPED 6U
#define SERIAL_MOTION_VALIDATION_COMMAND_ENABLED 1U
#define X_LIMIT_ACTIVE_MASK 0x0007U
#define Y_LIMIT_ACTIVE_MASK 0x0038U
/* Z-axis limit protection is enabled for the on-target limit test. */
#define Z_LIMIT_PROTECTION_ENABLED 1U
#define Z_LIMIT_ACTIVE_MASK 0x01C0U
#define Z_LIMIT_CHECK_MASK ((Z_LIMIT_PROTECTION_ENABLED != 0U) ? Z_LIMIT_ACTIVE_MASK : 0U)
#define X_MOTION_IHOLD 0U
#define X_MOTION_IRUN 3U
#define Y_MOTION_IHOLD 0U
#define Y_MOTION_IRUN 3U
/* Temporary Z motor test: reduced current; not hardware-verified. */
#define Z_MOTION_IHOLD 0U
#define Z_MOTION_IRUN 3U

#define SERIAL_TX_TIMEOUT_MS 100U
#define SERIAL_MOTION_GSTAT_CLEAR_DELAY_MS 100U
#define SERIAL_MOTION_ENABLE_DELAY_MS 200U
#define SERIAL_MOTION_DIRECTION_DELAY_MS 1U
#define X_MOTION_TOFF 3U
#define Y_MOTION_TOFF 3U
#define Z_MOTION_TOFF 3U
#define SERIAL_REQUEST_HEAD 0x55U
#define SERIAL_REQUEST_TAIL 0xAAU
#define SERIAL_RESPONSE_HEAD 0xAAU
#define SERIAL_RESPONSE_TAIL 0x55U
#define SERIAL_COMMAND_TEST 0x01U
#define SERIAL_COMMAND_MOTION 0x02U
#define SERIAL_COMMAND_RELAY 0x03U
#define SERIAL_COMMAND_BRAKE 0x04U
#define SERIAL_COMMAND_LIGHT 0x05U
#define SERIAL_SUBCOMMAND_DEFAULT 0x00U
#define SERIAL_SUBCOMMAND_STOP 0x02U
#define SERIAL_SUBCOMMAND_STATUS 0x03U
#define SERIAL_SUBCOMMAND_CONTINUOUS 0xF0U
#define SERIAL_MOTION_AXIS_X 0x01U
#define SERIAL_MOTION_AXIS_Y 0x02U
#define SERIAL_MOTION_AXIS_Z 0x03U
#define SERIAL_MOTION_AXIS_COUNT 3U
#define SERIAL_MOTION_DIRECTION_MAX 0x01U
#define SERIAL_STATUS_ACCEPTED 0x00U
#define SERIAL_STATUS_DONE 0x01U
#define SERIAL_STATUS_STOPPED 0x02U
#define SERIAL_STATUS_ERROR 0xFFU
#define SERIAL_AUX_ACTION_ON 0x01U
#define SERIAL_AUX_ACTION_OFF 0x02U
#define SERIAL_DATA_ZERO 0x00U
#define SERIAL_DATA_SIZE 8U
#define SERIAL_DATA_FIRST 4U
#define SERIAL_DATA_SECOND 5U
#define SERIAL_TAIL_FIRST 12U

/* Fixed byte positions; keep the original integer literal types. */
#define SERIAL_FRAME_HEAD0_INDEX 0
#define SERIAL_FRAME_HEAD1_INDEX 1
#define SERIAL_FRAME_COMMAND_INDEX 2
#define SERIAL_FRAME_SUBCOMMAND_INDEX 3
#define SERIAL_FRAME_DATA0_INDEX 4
#define SERIAL_FRAME_DATA1_INDEX 5
#define SERIAL_FRAME_DATA2_INDEX 6
#define SERIAL_FRAME_DATA3_INDEX 7
#define SERIAL_FRAME_DATA4_INDEX 8
#define SERIAL_FRAME_DATA5_INDEX 9
#define SERIAL_FRAME_DATA6_INDEX 10
#define SERIAL_FRAME_DATA7_INDEX 11
#define SERIAL_FRAME_TAIL0_INDEX 12
#define SERIAL_FRAME_TAIL1_INDEX 13
#define SERIAL_BYTE1_SHIFT 8
#define SERIAL_BYTE2_SHIFT 16
#define SERIAL_BYTE3_SHIFT 24
#endif /* MOTOR_CONFIG_H */
